import React from "react";
import { Link } from "react-router-dom";
import MainPage from "./MainPage/MainPage";
const Home = () => {
  return (
    <div className="container">
      {/* <MainPage/> */}
      <div className="dhiwise-navigation">
        <h1>Homepage</h1>
        <p className="headline">
          This project was generated By{" "}
          <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
          to navigate through all pages.
        </p>
        <ul>
          <li>
            <Link to="/baslinereporting">BaslineReporting</Link>
          </li>
          <li>
            <Link to="/customisedorderstatus">CustomisedOrderStatus</Link>
          </li>
          <li>
            <Link to="/ordertracking">OrderTracking</Link>
          </li>
          <li>
            <Link to="/expensetracking">ExpenseTracking</Link>
          </li>
          <li>
            <Link to="/expressdelivery">ExpressDelivery</Link>
          </li>
          <li>
            <Link to="/enablelinkedaccounts">EnableLinkedAccounts</Link>
          </li>
          <li>
            <Link to="/freecredits">FreeCredits</Link>
          </li>
          <li>
            <Link to="/review">Review</Link>
          </li>
          <li>
            <Link to="/requestmanagement">RequestManagement</Link>
          </li>
          <li>
            <Link to="/reviewapproval">ReviewApproval</Link>
          </li>
          <li>
            <Link to="/projectstracking">ProjectsTracking</Link>
          </li>
          <li>
            <Link to="/loyaltysystem">LoyaltySystem</Link>
          </li>
          <li>
            <Link to="/rfid">RFID</Link>
          </li>
          <li>
            <Link to="/taskviews">TaskViews</Link>
          </li>
        </ul>
        <p>dssal;kjf;lljaddsalkfj;lajsl;fkjal;kdlkanf;lkansd;lkfl;aksndlf;kn;lkdasn;lfkn;lakdn</p><br />
        <p>dssal;kjf;lljaddsalkfj;lajsl;fkjal;kdlkanf;lkansd;lkfl;aksndlf;kn;lkdasn;lfkn;lakdn</p><br />
        <p>dssal;kjf;lljaddsalkfj;lajsl;fkjal;kdlkanf;lkansd;lkfl;aksndlf;kn;lkdasn;lfkn;lakdn</p><br />
        <p>dssal;kjf;lljaddsalkfj;lajsl;fkjal;kdlkanf;lkansd;lkfl;aksndlf;kn;lkdasn;lfkn;lakdn</p><br />
      
      </div>
    </div>
  );
};
export default Home;
